name: simplebt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.6
  - numpy=1.19.4
  - pandas=1.2.0
  - pip=21.2.2
  - psycopg2-binary=2.8.6
  - pip:
      - "ib_insync==0.9.66"
      - "git+ssh://git@github.com/gipaetusb/trading_calendars#egg=trading_calendars"
